language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
notifications:
  email: false
before_install:
  # Update package.json semver based on the git tag we just created
  - npm version minor
  # TODO -- execute a script to update manifest based on version val in package.json
deploy:
  provider: script
  skip_cleanup: true
  script: git push
  on:
    branch: master
branches:
  only:
  - master
