language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: npm version minor && sh ./scripts/update-version.sh 
  on:
    branch: master
branches:
  only:
  - master
